services:
  - type: web
    name: sweety-gtg-webapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 90
    envVars:
      - key: ACCESS_CODE
        sync: false
      - key: SMTP_EMAIL
        value: amministrazione.swt@gmail.com
      - key: RESEND_API_KEY
        sync: false
      - key: CONFIRM_EMAIL
        sync: false
      - key: RATE_PER_CONTRACT
        value: "500"
      - key: FIXED_FEE
        value: "1000"
      - key: ADMIN_FEE
        value: "300"
      - key: SECRET_KEY
        sync: false
